// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../lu/albert/closure/fx/easing/easing.js', ['lu.albert.closure.fx.easing'], ['goog.debug.Logger']);
